#!/usr/bin/env python3
"""Raise compileSdk for every generated Android plugin subproject.

Why this exists
---------------
`flutter_blue_plus` declares `compileSdk 33`, but several AndroidX artifacts it
depends on now require their consumers to compile against 34+. Gradle enforces
that in `:flutter_blue_plus:checkReleaseAarMetadata`, so the release build dies
with "Dependency ... requires libraries and applications that depend on it to
compile against version 34 or later".

Nothing in the app can fix this: the failing module is the plugin's own, and
`android/` is regenerated by `flutter create` on every CI run, so the override
cannot simply be committed. Hence a build-time patch.

The alternative — bumping flutter_blue_plus 1.34 -> 2.3 — is a major version
with breaking API changes across both apps in this repo, and validating it
needs a full APK build.

Placement matters
-----------------
Flutter's generated root build file ends with:

    subprojects {
        project.evaluationDependsOn(":app")
    }

That forces evaluation of every subproject. Registering an `afterEvaluate`
callback *after* it throws:

    Cannot run Project.afterEvaluate(Action) when the project is already
    evaluated.

So the block is inserted before the FIRST `subprojects {` in the file, not
appended to the end.

Usage: run with the module's `android/` directory as the working directory.
"""

import pathlib
import sys

COMPILE_SDK = 35

KTS_BLOCK = """
// Injected by .github/scripts/raise_plugin_compilesdk.py — see that file.
// Must stay above Flutter's `subprojects { project.evaluationDependsOn(":app") }`,
// which evaluates the projects and makes a later afterEvaluate illegal.
subprojects {
    afterEvaluate {
        val androidExt = extensions.findByName("android")
        if (androidExt != null) {
            androidExt.withGroovyBuilder { "compileSdkVersion"(%d) }
        }
    }
}
""" % COMPILE_SDK

GROOVY_BLOCK = """
// Injected by .github/scripts/raise_plugin_compilesdk.py — see that file.
subprojects {
    afterEvaluate { p ->
        if (p.hasProperty('android')) {
            p.android { compileSdkVersion %d }
        }
    }
}
""" % COMPILE_SDK

MARKER = "raise_plugin_compilesdk.py"


def main() -> int:
    kts = pathlib.Path("build.gradle.kts")
    groovy = pathlib.Path("build.gradle")

    if kts.exists():
        path, block = kts, KTS_BLOCK
    elif groovy.exists():
        path, block = groovy, GROOVY_BLOCK
    else:
        print("ERROR: no root build.gradle(.kts) in", pathlib.Path.cwd(),
              file=sys.stderr)
        return 1

    src = path.read_text(encoding="utf-8")

    if MARKER in src:
        print(f"{path} already patched — nothing to do")
        return 0

    idx = src.find("subprojects {")
    if idx == -1:
        # No subprojects block to race with, so appending is safe.
        src = src + block
        where = "appended (no existing subprojects block)"
    else:
        src = src[:idx] + block.lstrip("\n") + "\n" + src[idx:]
        where = f"inserted at offset {idx}, before the first subprojects block"

    path.write_text(src, encoding="utf-8")
    print(f"Patched {path}: compileSdk {COMPILE_SDK} for all subprojects ({where})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
