#!/usr/bin/env python3
"""Raise compileSdk for the generated Android plugin subprojects that need it.

Why this exists
---------------
`flutter_blue_plus` declares `compileSdk 33`, but several AndroidX artifacts it
depends on now require their consumers to compile against 34+. Gradle enforces
that in `:flutter_blue_plus:checkReleaseAarMetadata`, so the release build dies
with "Dependency ... requires libraries and applications that depend on it to
compile against version 34 or later".

Nothing in the app can fix this: the failing module is the plugin's own, and
`android/` is regenerated by `flutter create` on every CI run, so the override
cannot simply be committed. Hence a build-time patch.

The alternative — bumping flutter_blue_plus 1.34 -> 2.3 — is a major version
with breaking API changes across both apps in this repo, and validating it
needs a full APK build.

Why an allowlist and not every subproject
-----------------------------------------
Raising *all* plugins broke `package_info_plus` 5.0.1, whose Kotlin reads
`PackageInfo.applicationInfo` and `PackageInfo.signatures` without null checks.
Those fields gained `@Nullable` in API 34, so compiling that plugin against 35
turns them into hard Kotlin errors:

    Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable
    receiver of type 'ApplicationInfo?'

flutter_blue_plus's Android code is Java, which ignores those annotations, so
raising only the module that actually fails the metadata check is safe.

Every android subproject is logged at lifecycle level, raised or not, so a
future metadata failure shows immediately which name to add to RAISE.

Placement matters
-----------------
Flutter's generated root build file ends with:

    subprojects {
        project.evaluationDependsOn(":app")
    }

That forces evaluation of every subproject. Registering an `afterEvaluate`
callback *after* it throws:

    Cannot run Project.afterEvaluate(Action) when the project is already
    evaluated.

So the block is inserted before the FIRST `subprojects {` in the file, not
appended to the end.

Usage: run with the module's `android/` directory as the working directory.
"""

import pathlib
import sys

COMPILE_SDK = 35

# Only modules that fail `checkReleaseAarMetadata`. See the docstring above for
# why this is not "every subproject".
RAISE = ["flutter_blue_plus"]

_KTS_NAMES = ", ".join('"%s"' % n for n in RAISE)
_GROOVY_NAMES = ", ".join("'%s'" % n for n in RAISE)

KTS_BLOCK = """
// Injected by .github/scripts/raise_plugin_compilesdk.py — see that file.
// Must stay above Flutter's `subprojects { project.evaluationDependsOn(":app") }`,
// which evaluates the projects and makes a later afterEvaluate illegal.
val raiseCompileSdk = setOf(%s)
subprojects {
    afterEvaluate {
        val androidExt = extensions.findByName("android")
        if (androidExt != null) {
            if (project.name in raiseCompileSdk) {
                androidExt.withGroovyBuilder { "compileSdkVersion"(%d) }
                logger.lifecycle("[compileSdk] raised ${project.name} -> android-%d")
            } else {
                logger.lifecycle("[compileSdk] left ${project.name} at its own value")
            }
        }
    }
}
""" % (_KTS_NAMES, COMPILE_SDK, COMPILE_SDK)

GROOVY_BLOCK = """
// Injected by .github/scripts/raise_plugin_compilesdk.py — see that file.
def raiseCompileSdk = [%s] as Set
subprojects {
    afterEvaluate { p ->
        if (p.hasProperty('android')) {
            if (raiseCompileSdk.contains(p.name)) {
                p.android { compileSdkVersion %d }
                p.logger.lifecycle("[compileSdk] raised ${p.name} -> android-%d")
            } else {
                p.logger.lifecycle("[compileSdk] left ${p.name} at its own value")
            }
        }
    }
}
""" % (_GROOVY_NAMES, COMPILE_SDK, COMPILE_SDK)

MARKER = "raise_plugin_compilesdk.py"


def main() -> int:
    kts = pathlib.Path("build.gradle.kts")
    groovy = pathlib.Path("build.gradle")

    if kts.exists():
        path, block = kts, KTS_BLOCK
    elif groovy.exists():
        path, block = groovy, GROOVY_BLOCK
    else:
        print("ERROR: no root build.gradle(.kts) in", pathlib.Path.cwd(),
              file=sys.stderr)
        return 1

    src = path.read_text(encoding="utf-8")

    if MARKER in src:
        print(f"{path} already patched — nothing to do")
        return 0

    idx = src.find("subprojects {")
    if idx == -1:
        # No subprojects block to race with, so appending is safe.
        src = src + block
        where = "appended (no existing subprojects block)"
    else:
        src = src[:idx] + block.lstrip("\n") + "\n" + src[idx:]
        where = f"inserted at offset {idx}, before the first subprojects block"

    path.write_text(src, encoding="utf-8")
    print(f"Patched {path}: compileSdk {COMPILE_SDK} for {RAISE} ({where})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
